source 'https://cdn.cocoapods.org/'
platform :ios, '17.0'

target 'iosApp' do
  use_frameworks!

  pod 'MyCocoaPod', :path => '../composeApp'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphone simulator*]'] = 'arm64'
    end
  end
end